### ISSUE TITLE
Tests fail on `1.6.0` and `1.5.0` with `ERROR do_EXPORT() missing 1 required positional argument: 'name'`

### ISSUE THREAD

**Issue by TheChymera** [Lykos153/AnnexRemote#61] opened 2023-01-13 06:52 UTC
Here is the full build log: https://ppb.chymera.eu/f21479.log

And these are the test failures:

```
======================================================================
FAIL: TestExport_MissingName (test_GitAnnexRequestMessages.TestGitAnnexRequestMessagesExporttree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/annexremote-1.6.0/work/annexremote-1.6.0/tests/test_GitAnnexRequestMessages.py", line 305, in TestExport_MissingName
    self.assertEqual(utils.last_buffer_line(self.output), "ERROR do_EXPORT() missing 1 required positional argument: 'name'")
AssertionError: "ERROR Protocol.do_EXPORT() missing 1 required positional argument: 'name'" != "ERROR do_EXPORT() missing 1 required positional argument: 'name'"
- ERROR Protocol.do_EXPORT() missing 1 required positional argument: 'name'
?       ---------
+ ERROR do_EXPORT() missing 1 required positional argument: 'name'


======================================================================
FAIL: TestRemoveexportdirectory_MissingDirectory (test_GitAnnexRequestMessages.TestGitAnnexRequestMessagesExporttree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/annexremote-1.6.0/work/annexremote-1.6.0/tests/test_GitAnnexRequestMessages.py", line 423, in TestRemoveexportdirectory_MissingDirectory
    self.assertEqual(utils.last_buffer_line(self.output), "ERROR do_REMOVEEXPORTDIRECTORY() missing 1 required positional argument: 'name'")
AssertionError: "ERROR Protocol.do_REMOVEEXPORTDIRECTORY() missi[37 chars]ame'" != "ERROR do_REMOVEEXPORTDIRECTORY() missing 1 requ[28 chars]ame'"
- ERROR Protocol.do_REMOVEEXPORTDIRECTORY() missing 1 required positional argument: 'name'
?       ---------
+ ERROR do_REMOVEEXPORTDIRECTORY() missing 1 required positional argument: 'name'


----------------------------------------------------------------------
```

Any idea what could be wrong?

Also, do you intend to switch to pytest or unittest in the forseeable future? It appears it [might be discontinued](https://nose.readthedocs.io/en/latest/).

**Comment by yarikoptic** [comment] 2023-02-14 02:36
duplicate of #33, the eldest wins

**Closed by yarikoptic** 2023-02-14 02:36 UTC
